// frontend/src/components/Footer.tsx
'use client';

import React from 'react';
import Link from 'next/link';
import { useTheme } from '@/context/ThemeContext';

export default function Footer() {
  const { theme } = useTheme();
  
  return (
    <footer className={`${theme === 'dark' ? 'bg-gray-800 text-white' : 'bg-gray-100 text-gray-600'} py-8`}>
      <div className="container mx-auto px-4">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div>
            <h3 className="text-lg font-semibold mb-4">PulseFitness</h3>
            <p className="text-sm">
              Your journey to fitness starts here. Join us and transform your life with expert guidance and support.
            </p>
          </div>
          <div>
            <h3 className="text-lg font-semibold mb-4">Quick Links</h3>
            <ul className="space-y-2">
              <li><Link href="/reservations" className="text-sm hover:text-indigo-500 transition-colors">Reservations</Link></li>
              <li><Link href="/products" className="text-sm hover:text-indigo-500 transition-colors">Products</Link></li>
              <li><Link href="/subscriptions" className="text-sm hover:text-indigo-500 transition-colors">Subscriptions</Link></li>
            </ul>
          </div>
          <div>
            <h3 className="text-lg font-semibold mb-4">Contact</h3>
            <ul className="space-y-2 text-sm">
              <li>Email: info@pulsefitness.com</li>
              <li>Phone: (123) 456-7890</li>
              <li>Address: 123 Fitness Street, Gym City</li>
            </ul>
          </div>
        </div>
        <div className="mt-8 pt-8 border-t border-gray-700 text-center text-sm">
          <p>&copy; {new Date().getFullYear()} PulseFitness. All rights reserved.</p>
        </div>
      </div>
    </footer>
  );
}

// frontend/components/footer.vue
<template>
    <footer class="bg-white dark:bg-dark-bg text-black dark:text-dark-text py-8">
      <div class="container mx-auto grid grid-cols-1 md:grid-cols-3 gap-6">
        <!-- About Section -->
        <div>
          <h2 class="text-lg font-bold text-blue dark:text-light-blue mb-4">About Us</h2>
          <p class="text-sm leading-relaxed">
            Welcome to <strong>Pulse Fitness Gym</strong>, the ultimate destination for fitness and strength. Our state-of-the-art facilities and expert trainers are here to help you achieve your goals.
          </p>
        </div>
  
        <!-- Quick Links -->
        <div>
          <h2 class="text-lg font-bold text-blue dark:text-light-blue mb-4">Quick Links</h2>
          <ul class="space-y-2">
            <li><a href="/programs" class="hover:text-blue dark:hover:text-light-blue">Programs</a></li>
            <li><a href="/membership" class="hover:text-blue dark:hover:text-light-blue">Membership</a></li>
            <li><a href="/schedule" class="hover:text-blue dark:hover:text-light-blue">Class Schedule</a></li>
            <li><a href="/contact" class="hover:text-blue dark:hover:text-light-blue">Contact Us</a></li>
          </ul>
        </div>
  
        <!-- Contact & Social Links -->
        <div>
          <h2 class="text-lg font-bold text-blue dark:text-light-blue mb-4">Contact Us</h2>
          <p class="text-sm">
            <strong>Address:</strong> 123 Fitness Lane, Flex City, FL 54321
          </p>
          <p class="text-sm">
            <strong>Email:</strong> <a href="mailto:contact@pulsefitness.com" class="text-blue dark:text-light-blue hover:underline">contact@pulsefitness.com</a>
          </p>
          <p class="text-sm">
            <strong>Phone:</strong> <a href="tel:+1234567890" class="text-blue dark:text-light-blue hover:underline">(123) 456-7890</a>
          </p>
          <div class="flex space-x-4 mt-4">
            <a href="#" class="hover:text-blue dark:hover:text-light-blue"><i class="fab fa-facebook-f"></i></a>
            <a href="#" class="hover:text-blue dark:hover:text-light-blue"><i class="fab fa-twitter"></i></a>
            <a href="#" class="hover:text-blue dark:hover:text-light-blue"><i class="fab fa-instagram"></i></a>
            <a href="#" class="hover:text-blue dark:hover:text-light-blue"><i class="fab fa-youtube"></i></a>
          </div>
        </div>
      </div>
  
      <!-- Footer Bottom -->
      <div class="mt-8 border-t border-dark-light-gray dark:border-dark-blue pt-4 text-center">
        <p class="text-sm">&copy; 2024 Pulse Fitness Gym. All rights reserved.</p>
        <p class="text-sm">"Strength, Dedication, Transformation"</p>
      </div>
    </footer>
  </template>
