// frontend/src/components/Navbar.tsx
'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useTheme } from '@/context/ThemeContext';
import { useAuth } from '@/context/AuthContext';
import { FiMoon, FiSun } from 'react-icons/fi';
import { FiShoppingCart } from 'react-icons/fi';

export default function Navbar() {
  const pathname = usePathname();
  const { theme, toggleTheme } = useTheme();
  const { isAuthenticated, logout } = useAuth();
  const isDark = theme === 'dark';

  const handleLogout = () => {
    logout();
  };

  return (
    <nav className={`fixed w-full z-50 top-0 ${isDark ? 'bg-gray-800' : 'bg-white'} shadow-md`}>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between h-16">
          <div className="flex">
            <div className="flex-shrink-0 flex items-center">
              <Link href="/" className={`text-2xl font-bold ${isDark ? 'text-white' : 'text-primary'}`}>
                Pulse Fitness
              </Link>
            </div>
            <div className="hidden sm:ml-6 sm:flex sm:space-x-8">
              <Link
                href="/home"
                className={`inline-flex items-center px-1 pt-1 text-sm font-medium ${
                  pathname === '/'
                    ? 'text-primary border-b-2 border-primary'
                    : isDark
                    ? 'text-gray-300 hover:text-white'
                    : 'text-gray-500 hover:text-gray-700'
                }`}
              >
                Home
              </Link>
              <Link
                href="/products"
                className={`inline-flex items-center px-1 pt-1 text-sm font-medium ${
                  pathname === '/products'
                    ? 'text-primary border-b-2 border-primary'
                    : isDark
                    ? 'text-gray-300 hover:text-white'
                    : 'text-gray-500 hover:text-gray-700'
                }`}
              >
                Products
              </Link>
              <Link
                href="/profile"
                className={`inline-flex items-center px-1 pt-1 text-sm font-medium ${
                  pathname === '/profile'
                    ? 'text-primary border-b-2 border-primary'
                    : isDark
                    ? 'text-gray-300 hover:text-white'
                    : 'text-gray-500 hover:text-gray-700'
                }`}
              >
                Profile
              </Link>
            </div>
          </div>
          <div className="flex items-center">
            {isAuthenticated && (
              <Link
                href="/cart" 
                className={`mr-4 ${isDark ? 'text-white' : 'text-gray-800'} hover:text-primary transition-colors`}
              >
                <FiShoppingCart size={20} />
              </Link>
            )}
            <button
              onClick={toggleTheme}
              className={`p-2 rounded-lg ${
                isDark ? 'text-white hover:bg-gray-700' : 'text-gray-800 hover:bg-gray-100'
              } transition-colors`}
              aria-label={isDark ? 'Switch to light mode' : 'Switch to dark mode'}
            >
              {isDark ? <FiSun size={20} /> : <FiMoon size={20} />}
            </button>
            <div className="ml-4">
              {isAuthenticated ? (
                <button
                  onClick={handleLogout}
                  className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-primary hover:bg-primary/90"
                >
                  Logout
                </button>
              ) : (
                <Link
                  href="/auth/login"
                  className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-primary hover:bg-primary/90"
                >
                  Login
                </Link>
              )}
            </div>
          </div>
        </div>
      </div>
    </nav>
  );
}

// frontend/components/nav-bar.vue
<template>
  <header class="bg-white dark:bg-black backdrop-blur-md py-4 px-6 fixed inset-x-0 top-0 z-50 shadow-lg">
    <div class="max-w-screen-xl mx-auto flex items-center justify-between">
      <!-- Logo Section -->
      <div class="flex items-center space-x-4">
        <NuxtImg
          src="/logo.png"
          alt="Logo"
          class="h-10 w-auto"
        />
        <NuxtLink to="/" class="text-black dark:text-white text-2xl font-extrabold tracking-wider">
          Pulse
        </NuxtLink>
      </div>
      
      <!-- Navigation Links (Desktop) -->
      <nav class="hidden md:flex space-x-6 font-semibold tracking-wide">
        <NuxtLink to="/nav/home" class="text-black dark:text-white hover:text-blue dark:hover:text-light-blue transition duration-300">
          Home
        </NuxtLink>
        <NuxtLink to="/nav/subscriptions" class="text-black dark:text-white hover:text-blue dark:hover:text-light-blue transition duration-300">
          Subscriptions
        </NuxtLink>
        <NuxtLink to="/nav/products" class="text-black dark:text-white hover:text-blue dark:hover:text-light-blue transition duration-300">
          Products
        </NuxtLink>
        <NuxtLink to="/nav/about" class="text-black dark:text-white hover:text-blue dark:hover:text-light-blue transition duration-300">
          About
        </NuxtLink>
      </nav>
      
      <!-- Dark Mode & Connect Button Wrapper (Desktop) -->
      <div class="hidden md:flex items-center space-x-4">
        <!-- Dark mode button -->
        <button
          @click="toggleDarkMode"
          class="dark-mode-toggle bg-gray-200 dark:bg-gray-800 text-gray-800 dark:text-gray-200 border border-gray-400 dark:border-gray-600 p-2 rounded-full transition-colors duration-300 ease-in-out"
          aria-label="Toggle Dark Mode"
        >
          <span v-if="!isDark">🌞</span>
          <span v-else>🌙</span>
        </button>

        <!-- Connect Button -->
        <NuxtLink to="/auth/login">
          <button class="btn-primary py-2 px-4 border hover:text-black border-blue dark:border-dark-blue text-black dark:text-white bg-blue dark:bg-dark-blue rounded-lg hover:bg-transparent dark:hover:bg-transparent hover:border-black dark:hover:border-white transition-all duration-300">
            Connect
          </button>
        </NuxtLink>
      </div>

      <!-- Mobile Menu Toggle Button -->
      <div class="md:hidden flex items-center">
        <button @click="toggleMenu" class="text-black dark:text-white">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
            <path
              stroke="currentColor"
              stroke-width="2"
              d="M4 6h16M4 12h16M4 18h16"
            />
          </svg>
        </button>
      </div>
    </div>

    <!-- Mobile Menu -->
    <transition name="fade">
      <div
        v-if="isMenuOpen"
        @click="toggleMenu"
        class="md:hidden bg-white dark:bg-black backdrop-blur-lg p-6 absolute top-16 left-0 right-0 z-40 shadow-lg"
      >
        <NuxtLink to="/" class="block text-black dark:text-white py-2 hover:text-blue dark:hover:text-light-blue">
          Home
        </NuxtLink>
        <NuxtLink to="/about" class="block text-black dark:text-white py-2 hover:text-blue dark:hover:text-light-blue">
          Subscriptions
        </NuxtLink>
        <NuxtLink to="/services" class="block text-black dark:text-white py-2 hover:text-blue dark:hover:text-light-blue">
          Products
        </NuxtLink>
        <NuxtLink to="/contact" class="block text-black dark:text-white py-2 hover:text-blue dark:hover:text-light-blue">
          About
        </NuxtLink>
        <button
          @click="toggleDarkMode"
          class="dark-mode-toggle bg-gray-200 dark:bg-gray-800 text-gray-800 dark:text-gray-200 border border-gray-400 dark:border-gray-600 p-2 rounded-full transition-colors duration-300 ease-in-out"
          aria-label="Toggle Dark Mode"
        >
          <span v-if="!isDark">🌞</span>
          <span v-else>🌙</span>
        </button>
        <NuxtLink to="/auth/login">
          <button
            class="w-full btn-primary py-2 mt-4 border hover:text-black border-blue dark:border-dark-blue text-black dark:text-white bg-blue dark:bg-dark-blue rounded-lg hover:bg-transparent dark:hover:bg-transparent hover:border-black dark:hover:border-white transition-all duration-300"
          >
            Connect
          </button>
        </NuxtLink>
      </div>
    </transition>
  </header>
</template>


<script setup>
import { useDarkMode } from '~/composables/useDarkMode';

const { isDark, toggleDarkMode } = useDarkMode();


import { ref } from 'vue';

const isMenuOpen = ref(false); 

const toggleMenu = () => {
  isMenuOpen.value = !isMenuOpen.value; 
};

</script>

<style scoped>
@import url('https://fonts.googleapis.com/icon?family=Material+Icons');

</style>
