// frontend/pages/auth/login.vue
<template>
  <div class="h-screen dark:bg-dark-bg flex items-center justify-center">
    <div id="container" class="bg-light-gray w-1/4 rounded-xl content-center p-5 h-auto shadow-xl hover:shadow-lg-white transition duration-300 relative">
      <form @submit.prevent="handleLogin">
        <!-- Dark Mode Toggle Button -->
        <div class="flex justify-end">
          <button
            @click="toggleDarkMode"
            class="dark-mode-toggle bg-gray-200 dark:bg-dark-gray text-gray-800 dark:text-dark-text border border-gray-400 dark:border-dark-light-gray p-2 rounded-full transition-colors duration-300 ease-in-out mb-4"
            aria-label="Toggle Dark Mode"
          >
            <span v-if="!isDark">🌞</span>
            <span v-else>🌙</span>
          </button>
        </div>

        <!-- Login Heading -->
        <h2 class="text-center text-black dark:text-dark-text text-h2 mb-8">Login</h2>

        <!-- Email Input -->
        <div class="flex flex-col items-center mb-4">
          <label for="email" class="block text-black dark:text-dark-text mb-2">Email</label>
          <input
            v-model="formData.email"
            type="email"
            id="email"
            class="w-3/4 bg-transparent border-b-2 focus:placeholder:text-white dark:focus:placeholder:text-white border-black dark:border-dark-light-gray text-white dark:text-dark-text focus:shadow-bottom-white dark:focus:shadow-bottom-dark-blue placeholder-black dark:placeholder-dark-light-gray focus:outline-none focus:border-white dark:focus:border-dark-blue py-2 transition duration-300"
            required
            placeholder="Enter your email"
          />
        </div>

        <!-- Password Input -->
        <div class="flex flex-col items-center mb-4">
          <label for="password" class="block text-black dark:text-dark-text mb-2">Password</label>
          <input
            v-model="formData.password"
            type="password"
            id="password"
            class="w-3/4 bg-transparent border-b-2 focus:placeholder:text-white dark:focus:placeholder:text-white border-black dark:border-dark-light-gray text-white dark:text-dark-text focus:shadow-bottom-white dark:focus:shadow-bottom-dark-blue placeholder-black dark:placeholder-dark-light-gray focus:outline-none focus:border-white dark:focus:border-dark-blue py-2 transition duration-300"
            required
            placeholder="Enter your password"
          />
        </div>

        <!-- Login Redirect -->
        <div class="flex flex-col items-center mb-4">
          <span class="text-black dark:text-dark-text">Don't have an account?
            <NuxtLink to="/auth/register" class="text-blue dark:text-dark-blue hover:text-light-blue dark:hover:text-blue transition duration-300">
              Register
            </NuxtLink>
          </span>
        </div>

        <!-- Login Button -->
        <div class="flex flex-col items-center mb-4">
          <button class="text-black dark:text-dark-text bg-blue dark:bg-dark-blue hover:bg-blue dark:hover:bg-blue transition duration-300 rounded px-4 py-2"
          type="submit"
          >
            Login
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup>
import { useDarkMode } from '~/composables/useDarkMode';
const { isDark, toggleDarkMode } = useDarkMode();

const formData = ref({
  email: '',
  password: ''
});

async function handleLogin() {
  try {
    const response = await $fetch('http://127.0.0.1:8000/api/login', {
      method: 'POST', 
      body: formData.value, 
    });
    console.log('Login successful:', response);
    alert('Login successful! Redirecting to home...');
    navigateTo('/nav/home'); 
  } catch (error) {
    console.error('Login error:', error);
    alert(error?.data?.message || 'An error occurred during login.');
  }
}


definePageMeta({
  layout: 'no-navbar'
});
</script>

// frontend/src/app/auth/login/page.tsx
"use client"

import type React from "react"

import { useState } from "react"
import { useRouter } from "next/navigation"
import Link from "next/link"
import { useTheme } from "@/context/ThemeContext"
import Cookies from "js-cookie"

export default function LoginPage() {
  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")
  const [error, setError] = useState("")
  const [isLoading, setIsLoading] = useState(false)
  const router = useRouter()
  const { theme } = useTheme()

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsLoading(true)
    setError("")

    try {
      const response = await fetch("http://localhost:8000/api/auth/login", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ email, password }),
      })

      const data = await response.json()

      if (!response.ok) {
        throw new Error(data.message || "Login failed")
      }

      // Store token in cookie instead of localStorage
      Cookies.set("token", data.token, { expires: 7 }) // Expires in 7 days

      router.push("/")
    } catch (err) {
      setError(err instanceof Error ? err.message : "An error occurred during login")
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div
      className={`min-h-screen flex items-center justify-center ${theme === "dark" ? "bg-gray-900 text-white" : "bg-gray-50 text-gray-900"}`}
    >
      <div className={`max-w-md w-full p-8 rounded-lg shadow-lg ${theme === "dark" ? "bg-gray-800" : "bg-white"}`}>
        <h1 className="text-3xl font-bold text-center mb-6">Login to Pulse Fitness</h1>

        {error && <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4">{error}</div>}

        <form onSubmit={handleSubmit} className="space-y-6">
          <div>
            <label htmlFor="email" className="block text-sm font-medium mb-1">
              Email
            </label>
            <input
              id="email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className={`w-full px-3 py-2 border rounded-md ${theme === "dark" ? "bg-gray-700 border-gray-600" : "bg-white border-gray-300"}`}
              required
            />
          </div>

          <div>
            <label htmlFor="password" className="block text-sm font-medium mb-1">
              Password
            </label>
            <input
              id="password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className={`w-full px-3 py-2 border rounded-md ${theme === "dark" ? "bg-gray-700 border-gray-600" : "bg-white border-gray-300"}`}
              required
            />
          </div>

          <div className="flex items-center justify-between">
            <div className="flex items-center">
              <input
                id="remember-me"
                type="checkbox"
                className="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded"
              />
              <label htmlFor="remember-me" className="ml-2 block text-sm">
                Remember me
              </label>
            </div>

            <div className="text-sm">
              <Link href="/auth/forgot-password" className="text-indigo-600 hover:text-indigo-500">
                Forgot your password?
              </Link>
            </div>
          </div>

          <button
            type="submit"
            disabled={isLoading}
            className="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
          >
            {isLoading ? "Logging in..." : "Sign in"}
          </button>
        </form>

        <div className="mt-6">
          <div className="relative">
            <div className="absolute inset-0 flex items-center">
              <div className={`w-full border-t ${theme === "dark" ? "border-gray-600" : "border-gray-300"}`}></div>
            </div>
          </div>
        </div>

        <p className="mt-6 text-center text-sm">
          Don't have an account?{" "}
          <Link href="/auth/register" className="text-indigo-600 hover:text-indigo-500">
            Sign up
          </Link>
        </p>
      </div>
    </div>
  )
}
