// frontend/pages/auth/register.vue
<template>
  <div class="h-screen flex items-center justify-center bg-white dark:bg-dark-bg">
    <div
      id="container"
      class="relative bg-black dark:bg-dark-gray w-1/4 h-auto rounded-xl p-5 shadow-xl hover:shadow-lg-white transition duration-300"
    >
      <button
        @click="toggleDarkMode"
        class="absolute top-4 right-4 dark-mode-toggle bg-gray-200 dark:bg-gray-800 text-gray-800 dark:text-gray-200 border border-gray-400 dark:border-gray-600 p-2 rounded-full transition-colors duration-300 ease-in-out"
        aria-label="Toggle Dark Mode"
      >
        <span v-if="!isDark">🌞</span>
        <span v-else>🌙</span>
      </button>
      <h2 class="text-center text-white dark:text-dark-text text-2xl mb-8">Register</h2>
      
      <form @submit.prevent="handleRegister">
        <!-- Step 1 -->
        <div v-if="step === 1">
          <div class="flex flex-col items-center mb-4">
            <label for="email" class="block text-white dark:text-dark-text mb-2">Email</label>
            <input
              v-model="formData.email"
              type="email"
              id="email"
              class="w-3/4 bg-transparent border-b-2 dark:focus:placeholder:text-white border-gray-400 dark:border-dark-light-gray text-white dark:text-dark-text focus:shadow-bottom-white dark:focus:shadow-bottom-dark-blue placeholder-gray-400 dark:placeholder-dark-light-gray focus:outline-none focus:border-white dark:focus:border-dark-blue py-2 transition duration-300"
              required
              placeholder="Enter your email"
            />
          </div>

          <div class="flex flex-col items-center mb-4">
            <label for="name" class="block text-white dark:text-dark-text mb-2">Name</label>
            <input
              v-model="formData.name"
              type="text"
              id="name"
              class="w-3/4 bg-transparent border-b-2 dark:focus:placeholder:text-white border-gray-400 dark:border-dark-light-gray text-white dark:text-dark-text focus:shadow-bottom-white dark:focus:shadow-bottom-dark-blue placeholder-gray-400 dark:placeholder-dark-light-gray focus:outline-none focus:border-white dark:focus:border-dark-blue py-2 transition duration-300"
              required
              placeholder="Enter your name"
            />
          </div>

          <div class="flex flex-col items-center mb-4">
            <label for="lastname" class="block text-white dark:text-dark-text mb-2">Last Name</label>
            <input
              v-model="formData.lastname"
              type="text"
              id="lastname"
              class="w-3/4 bg-transparent border-b-2 dark:focus:placeholder:text-white border-gray-400 dark:border-dark-light-gray text-white dark:text-dark-text focus:shadow-bottom-white dark:focus:shadow-bottom-dark-blue placeholder-gray-400 dark:placeholder-dark-light-gray focus:outline-none focus:border-white dark:focus:border-dark-blue py-2 transition duration-300"
              required
              placeholder="Enter your last name"
            />
          </div>

          <div class="flex flex-col items-center mb-4">
            <label for="password" class="block text-white dark:text-dark-text mb-2">Password</label>
            <input
              v-model="formData.password"
              type="password"
              id="password"
              class="w-3/4 bg-transparent border-b-2 dark:focus:placeholder:text-white border-gray-400 dark:border-dark-light-gray text-white dark:text-dark-text focus:shadow-bottom-white dark:focus:shadow-bottom-dark-blue placeholder-gray-400 dark:placeholder-dark-light-gray focus:outline-none focus:border-white dark:focus:border-dark-blue py-2 transition duration-300"
              required
              placeholder="Enter your password"
            />
          </div>

          <div class="flex flex-col items-center mb-4">
            <label for="password_confirmation" class="block text-white dark:text-dark-text mb-2">Password Confirmation</label>
            <input
              v-model="formData.password_confirmation"
              type="password"
              id="password_confirmation"
              class="w-3/4 bg-transparent border-b-2 dark:focus:placeholder:text-white border-gray-400 dark:border-dark-light-gray text-white dark:text-dark-text focus:shadow-bottom-white dark:focus:shadow-bottom-dark-blue placeholder-gray-400 dark:placeholder-dark-light-gray focus:outline-none focus:border-white dark:focus:border-dark-blue py-2 transition duration-300"
              required
              placeholder="Confirm your password"
            />
          </div>
        </div>

        <!-- Step 2 -->
        <div v-if="step === 2">
          <div class="flex flex-col items-center mb-4">
            <label for="birthdate" class="block text-white dark:text-dark-text mb-2">Birthdate</label>
            <input
              v-model="formData.birthdate"
              type="date"
              id="birthdate"
              class="w-3/4 bg-transparent border-b-2 dark:focus:placeholder:text-white border-gray-400 dark:border-dark-light-gray text-white dark:text-dark-text focus:shadow-bottom-white dark:focus:shadow-bottom-dark-blue placeholder-gray-400 dark:placeholder-dark-light-gray focus:outline-none focus:border-white dark:focus:border-dark-blue py-2 transition duration-300"
              placeholder="Enter your birthdate"
            />
          </div>

          <div class="flex flex-col items-center mb-4">
            <label for="gender" class="text-white dark:text-dark-text">Gender</label>
            <div class="flex items-center">
              <input v-model="formData.gender" type="radio" id="male" name="gender" value="male" class="mr-2" />
              <label for="male" class="text-white dark:text-dark-text">Male</label>
            </div>
            <div class="flex items-center">
              <input v-model="formData.gender" type="radio" id="female" name="gender" value="female" class="mr-2" />
              <label for="female" class="text-white dark:text-dark-text">Female</label>
            </div>
            <div class="flex items-center">
              <input v-model="formData.gender" type="radio" id="other" name="gender" value="other" class="mr-2" />
              <label for="other" class="text-white dark:text-dark-text">Other</label>
            </div>
          </div>

          <div class="flex flex-col items-center mb-4">
            <label for="phonenumber" class="block text-white dark:text-dark-text mb-2">Phone Number</label>
            <input
              v-model="formData.phone"
              type="tel"
              id="phonenumber"
              class="w-3/4 bg-transparent border-b-2 dark:focus:placeholder:text-white border-gray-400 dark:border-dark-light-gray text-white dark:text-dark-text focus:shadow-bottom-white dark:focus:shadow-bottom-dark-blue placeholder-gray-400 dark:placeholder-dark-light-gray focus:outline-none focus:border-white dark:focus:border-dark-blue py-2 transition duration-300"
              required
              placeholder="Enter your phone number"
            />
          </div>
        </div>

        <!-- Navigation Buttons -->
        <div class="flex justify-between mt-6">
          <button
            v-if="step > 1"
            type="button"
            @click="step--"
            class="text-white dark:text-dark-text bg-gray-500 hover:bg-gray-700 dark:bg-dark-blue transition duration-300 rounded px-4 py-2"
          >
            Back
          </button>
          <button
            v-if="step === 1"
            type="button"
            @click="validateStep1"
            class="text-white dark:text-dark-text bg-blue dark:bg-dark-blue hover:bg-blue dark:hover:bg-blue transition duration-300 rounded px-4 py-2"
          >
            Next
          </button>
          <button
            v-if="step === 2"
            type="submit"
            class="text-white align-self-center dark:text-dark-text bg-blue dark:bg-dark-blue hover:bg-blue dark:hover:bg-blue transition duration-300 rounded px-4 py-2"
          >
            Register
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup>
import { useDarkMode } from '~/composables/useDarkMode';
import { ref } from 'vue';

const { isDark, toggleDarkMode } = useDarkMode();
const step = ref(1);
const formData = ref({
  email: '',
  name: '',
  lastname: '',
  password: '',
  password_confirmation: '',
  birthdate: '',
  gender: '',
  phone: '',
});

async function handleRegister() {
  try {
    const response = await $fetch('http://127.0.0.1:8000/api/register', {
      method: 'POST',
      body: formData.value,
    });
    console.log('Registration successful:', response);
    alert('Registration successful!');
    $router.push('/auth/login');
  } catch (error) {
    console.error('Registration error:', error);
    const errorMessage = error?.data?.message || 'An error occurred during registration.';
    alert(errorMessage);
  }
}


function validateStep1() {
  if (!formData.value.email || !formData.value.name || !formData.value.lastname || !formData.value.password || !formData.value.password_confirmation) {
    alert('Please fill all fields');
    return;
  }
  if (formData.value.password !== formData.value.password_confirmation) {
    alert('Passwords do not match');
    return;
  }
  step.value++;
}


definePageMeta({
  layout: 'no-navbar'
});
</script>

// frontend/src/app/auth/register/page.tsx
'use client';

import type React from 'react';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { FiUser, FiMail, FiLock, FiCalendar, FiMapPin, FiSun, FiMoon, FiPhone, FiArrowRight } from 'react-icons/fi';
import { useTheme } from '@/context/ThemeContext';
import countryList from 'react-select-country-list';
import Select from 'react-select';
import Image from 'next/image';

interface FormData {
  name: string;
  lastname: string;
  email: string;
  password: string;
  password_confirmation: string;
  dob: string;
  country: string;
  phone: string;
  city: string;
  address: string;
  postalcode: string;
}

interface CountryOption {
  label: string;
  value: string;
}

export default function RegisterPage() {
  const router = useRouter();
  const { theme, toggleTheme } = useTheme();
  const isDark = theme === 'dark';

  const [formData, setFormData] = useState<FormData>({
    name: '',
    lastname: '',
    email: '',
    password: '',
    password_confirmation: '',
    dob: '',
    country: '',
    phone: '',
    city: '',
    address: '',
    postalcode: '',
  });

  const countries = countryList().getData() as CountryOption[];
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [step, setStep] = useState(1); // For multi-step form

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleCountryChange = (selectedOption: CountryOption | null) => {
    setFormData((prev) => ({ ...prev, country: selectedOption ? selectedOption.value : '' }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setError('');

    try {
      console.log("Registration data being sent:", formData);
      
      const response = await fetch('http://localhost:8000/api/auth/register', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData),
        credentials: 'include',
      });

      console.log("Registration response status:", response.status);
      
      // Handle non-JSON responses (like HTML error pages)
      const contentType = response.headers.get('content-type');
      if (contentType && contentType.indexOf('application/json') === -1) {
        const htmlError = await response.text();
        console.error("Non-JSON response received:", htmlError);
        throw new Error('Server error: The server returned an invalid response');
      }

      const data = await response.json();
      console.log("Registration response data:", data);

      if (!response.ok) {
        throw new Error(data.message || 'Registration failed');
      }

      router.push('/auth/login');
    } catch (err) {
      console.error("Registration error:", err);
      setError(err instanceof Error ? err.message : 'An error occurred during registration');
    } finally {
      setIsLoading(false);
    }
  };

  const nextStep = () => {
    if (step === 1) {
      // Validate first step fields
      if (!formData.name || !formData.lastname || !formData.email || !formData.password || !formData.password_confirmation) {
        setError('Please fill in all required fields');
        return;
      }
      if (formData.password !== formData.password_confirmation) {
        setError('Passwords do not match');
        return;
      }
    }
    setError('');
    setStep(step + 1);
  };

  const prevStep = () => {
    setStep(step - 1);
  };

  const renderFormStep = () => {
    if (step === 1) {
      return (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className={`block text-sm font-medium mb-1 ${isDark ? 'text-gray-200' : 'text-gray-700'}`}>First Name</label>
            <input
              type="text"
              name="name"
              value={formData.name}
              onChange={handleChange}
              className={`w-full px-3 py-2 border rounded-md ${isDark ? "bg-gray-700 border-gray-600 text-white" : "bg-white border-gray-300"}`}
              required
              placeholder="First Name"
            />
          </div>
          
          <div>
            <label className={`block text-sm font-medium mb-1 ${isDark ? 'text-gray-200' : 'text-gray-700'}`}>Last Name</label>
            <input
              type="text"
              name="lastname"
              value={formData.lastname}
              onChange={handleChange}
              className={`w-full px-3 py-2 border rounded-md ${isDark ? "bg-gray-700 border-gray-600 text-white" : "bg-white border-gray-300"}`}
              required
              placeholder="Last Name"
            />
          </div>
          
          <div className="md:col-span-2">
            <label className={`block text-sm font-medium mb-1 ${isDark ? 'text-gray-200' : 'text-gray-700'}`}>Email</label>
            <input
              type="email"
              name="email"
              value={formData.email}
              onChange={handleChange}
              className={`w-full px-3 py-2 border rounded-md ${isDark ? "bg-gray-700 border-gray-600 text-white" : "bg-white border-gray-300"}`}
              required
              placeholder="your.email@example.com"
            />
          </div>
          
          <div>
            <label className={`block text-sm font-medium mb-1 ${isDark ? 'text-gray-200' : 'text-gray-700'}`}>Password</label>
            <input
              type="password"
              name="password"
              value={formData.password}
              onChange={handleChange}
              className={`w-full px-3 py-2 border rounded-md ${isDark ? "bg-gray-700 border-gray-600 text-white" : "bg-white border-gray-300"}`}
              required
              placeholder="Password"
            />
          </div>
          
          <div>
            <label className={`block text-sm font-medium mb-1 ${isDark ? 'text-gray-200' : 'text-gray-700'}`}>Confirm Password</label>
            <input
              type="password"
              name="password_confirmation"
              value={formData.password_confirmation}
              onChange={handleChange}
              className={`w-full px-3 py-2 border rounded-md ${isDark ? "bg-gray-700 border-gray-600 text-white" : "bg-white border-gray-300"}`}
              required
              placeholder="Confirm Password"
            />
          </div>
          
          <div className="md:col-span-2 mt-4">
            <button
              type="button"
              onClick={nextStep}
              className="w-full py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
            >
              Continue <FiArrowRight className="inline ml-1" />
            </button>
            <p className="text-xs text-center mt-2 text-gray-500">
              By creating an account, you agree to our terms and conditions and gain access to premium equipment, supplements, and apparel.
            </p>
          </div>
        </div>
      );
    } else {
      return (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className={`block text-sm font-medium mb-1 ${isDark ? 'text-gray-200' : 'text-gray-700'}`}>Date of Birth</label>
            <input
              type="date"
              name="dob"
              value={formData.dob}
              onChange={handleChange}
              className={`w-full px-3 py-2 border rounded-md ${isDark ? "bg-gray-700 border-gray-600 text-white" : "bg-white border-gray-300"}`}
              required
            />
          </div>
          
          <div>
            <label className={`block text-sm font-medium mb-1 ${isDark ? 'text-gray-200' : 'text-gray-700'}`}>Phone</label>
            <input
              type="tel"
              name="phone"
              value={formData.phone}
              onChange={handleChange}
              className={`w-full px-3 py-2 border rounded-md ${isDark ? "bg-gray-700 border-gray-600 text-white" : "bg-white border-gray-300"}`}
              required
              placeholder="Phone Number"
            />
          </div>
          
          <div className="md:col-span-2">
            <label className={`block text-sm font-medium mb-1 ${isDark ? 'text-gray-200' : 'text-gray-700'}`}>Country</label>
            <Select
              options={countries}
              value={countries.find((c) => c.value === formData.country)}
              onChange={handleCountryChange}
              className="w-full"
              placeholder="Select a country"
              styles={{
                control: (base) => ({
                  ...base,
                  backgroundColor: isDark ? '#374151' : 'white',
                  borderColor: isDark ? '#4B5563' : '#D1D5DB',
                }),
                menu: (base) => ({
                  ...base,
                  backgroundColor: isDark ? '#374151' : 'white',
                }),
                option: (base, state) => ({
                  ...base,
                  backgroundColor: state.isFocused 
                    ? isDark ? '#4B5563' : '#F3F4F6'
                    : isDark ? '#374151' : 'white',
                  color: isDark ? 'white' : 'black',
                }),
                singleValue: (base) => ({
                  ...base,
                  color: isDark ? 'white' : 'black',
                }),
              }}
            />
          </div>
          
          <div>
            <label className={`block text-sm font-medium mb-1 ${isDark ? 'text-gray-200' : 'text-gray-700'}`}>City</label>
            <input
              type="text"
              name="city"
              value={formData.city}
              onChange={handleChange}
              className={`w-full px-3 py-2 border rounded-md ${isDark ? "bg-gray-700 border-gray-600 text-white" : "bg-white border-gray-300"}`}
              required
              placeholder="City"
            />
          </div>
          
          <div>
            <label className={`block text-sm font-medium mb-1 ${isDark ? 'text-gray-200' : 'text-gray-700'}`}>Postal Code</label>
            <input
              type="text"
              name="postalcode"
              value={formData.postalcode}
              onChange={handleChange}
              className={`w-full px-3 py-2 border rounded-md ${isDark ? "bg-gray-700 border-gray-600 text-white" : "bg-white border-gray-300"}`}
              required
              placeholder="Postal Code"
            />
          </div>
          
          <div className="md:col-span-2">
            <label className={`block text-sm font-medium mb-1 ${isDark ? 'text-gray-200' : 'text-gray-700'}`}>Address</label>
            <input
              type="text"
              name="address"
              value={formData.address}
              onChange={handleChange}
              className={`w-full px-3 py-2 border rounded-md ${isDark ? "bg-gray-700 border-gray-600 text-white" : "bg-white border-gray-300"}`}
              required
              placeholder="Address"
            />
          </div>
          
          <div className="md:col-span-2 mt-4 flex gap-4">
            <button
              type="button"
              onClick={prevStep}
              className={`w-1/3 py-2 px-4 border rounded-md shadow-sm text-sm font-medium ${
                isDark 
                  ? 'border-gray-600 text-white hover:bg-gray-700' 
                  : 'border-gray-300 text-gray-700 hover:bg-gray-50'
              } transition-colors`}
            >
              Back
            </button>
            <button
              type="submit"
              className="w-2/3 flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
              disabled={isLoading}
            >
              {isLoading ? 'Creating Account...' : 'Complete Registration'}
            </button>
          </div>
        </div>
      );
    }
  };

  return (
    <div className={`min-h-screen flex items-center justify-center ${isDark ? 'bg-gray-900 text-white' : 'bg-gray-50 text-gray-900'}`}>
      <div className="absolute top-4 right-4">
        <button
          onClick={toggleTheme}
          className="p-2 rounded-full bg-gray-200 dark:bg-gray-700 focus:outline-none"
          aria-label="Toggle theme"
        >
          {isDark ? <FiSun className="text-yellow-400" /> : <FiMoon className="text-gray-700" />}
        </button>
      </div>

      <div className="w-full max-w-6xl flex flex-col md:flex-row shadow-xl rounded-xl overflow-hidden">
        {/* Left side - Branding */}
        <div className="hidden md:flex md:w-1/3 bg-indigo-600 text-white p-10 flex-col justify-between">
          <div className="flex flex-col justify-center items-center h-full text-white p-12">
            <h1 className="text-4xl font-bold mb-4">Pulse Fitness</h1>
            <p className="text-xl mb-6 text-center">
              Your journey to a healthier lifestyle starts here.
            </p>
            <div className="w-16 h-1 bg-white rounded-full mb-8"></div>
          </div>
        </div>

        {/* Right side - Form */}
        <div className={`w-full md:w-2/3 p-8 ${isDark ? "bg-gray-800" : "bg-white"}`}>
          <div className="mb-6">
            <h2 className={`text-2xl font-bold ${isDark ? "text-white" : "text-gray-900"}`}>
              Create Your Account
            </h2>
            <p className={`text-sm ${isDark ? "text-gray-300" : "text-gray-600"}`}>
              Step {step} of 2: {step === 1 ? "Account Details" : "Personal Information"}
            </p>
            
            {/* Progress bar */}
            <div className="w-full h-2 bg-gray-200 rounded-full mt-4 mb-6">
              <div 
                className="h-full bg-indigo-600 rounded-full" 
                style={{ width: step === 1 ? "50%" : "100%" }}
              ></div>
            </div>
            
            {step === 1 && (
              <div>
                <h3 className={`text-lg font-medium mb-2 ${isDark ? "text-white" : "text-gray-900"}`}>
                  Account Information
                </h3>
                <p className={`text-sm mb-4 ${isDark ? "text-gray-300" : "text-gray-600"}`}>
                  Basic information to create your account.
                </p>
              </div>
            )}
            
            {step === 2 && (
              <div>
                <h3 className={`text-lg font-medium mb-2 ${isDark ? "text-white" : "text-gray-900"}`}>
                  Personal Information
                </h3>
                <p className={`text-sm mb-4 ${isDark ? "text-gray-300" : "text-gray-600"}`}>
                  Additional information for shipping and communication.
                </p>
              </div>
            )}
          </div>

          {error && (
            <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4">
              {error}
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-4">
            {renderFormStep()}
          </form>

          <div className="mt-6">
            <div className="relative">
              <div className="absolute inset-0 flex items-center">
                <div className={`w-full border-t ${isDark ? "border-gray-600" : "border-gray-300"}`}></div>
              </div>
              <div className="relative flex justify-center text-sm">
                <span className={`px-2 ${isDark ? "bg-gray-800" : "bg-white"} ${isDark ? "text-gray-300" : "text-gray-600"}`}>
                  Or
                </span>
              </div>
            </div>
            <p className="mt-4 text-center text-sm">
              Already have an account?{" "}
              <Link href="/auth/login" className="text-indigo-600 hover:text-indigo-500">
                Login
              </Link>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
